language: python

env:
  global:
    # Doctr deploy key for livecli/livecli.github.io
    - secure: "4lcIcK3mZlkdCWtsTB17bhCj+zAOH162qO7f3Q/Fe7hc8usbBzf5aN3kZpGmlk3Mt4GSEdYpJqZuWujgxRCKD0WlR/kk9YTHI+aZ36rpoe8hwP4SwvoqOxFOupai3/gjWL2meoWgZtP31jJk/duvnMVq8UizCHvB/27v+X9WuJJ7sUvsx7uKrc94PiiJD3cGN5Oh7RGww1MQyUfiRRoIzAuEJQT2uN7wcDQblxJJONyw2vtYVZlyN+nUvlNYDYgBOfb5dqnoNtUDVi+dNgouyhE1k8Ct5WlCMEF+wt2598kPmbTgCAJ+Cm/Ene/H8t9Rq7KdW3XBfsKqPbc5/7miYxHRjlMKfx+6aDV3LOR5MCuxy2RqESQ4fC0a0IjHQS0OOuYQXjLn4+sjS0DGWOCmoXKcgbKB0+UioeuPqf8PfAsbmZ4b8RlgQ1JlaOt2kFQ+JDt4tNNZs/db9Xqa6h9Tm6Hp7NsvzAypto8x1lEQ3BmJuiKx3+2/4FO4kyLshpEf4GJoCsQHT3S1SY1wSDq1q3q0nx6TmUfQZkOkrsbvhU/GB4F4W1iyTV6jkU/61mCBqVECC0SYz+MUZwnc29m7m/d5SFkMlNYDTFhqwDhN51tX8lCDdwRzdH2793SVMg18xQdl0PvXikNkw1seZs/5swpiJd/2ECHNoaSp7bIKnU0="

matrix:
  include:
  - python: '2.7'
  - python: '3.4'
  - python: '3.5'
    env: BUILD_DOCS=yes BUILD_INSTALLER=yes LIVECLI_INSTALLER_DIST_DIR=$TRAVIS_BUILD_DIR/dist/nsis
  - python: '3.6'
  - python: '3.7-dev'
  allow_failures:
  - python: '2.6'
  - python: '3.7-dev'

before_install:
  - pip install -U pip setuptools
  - pip install -r dev-requirements.txt
  - pip install pycountry
  - if [[ $BUILD_DOCS == 'yes' ]]; then
      pip install -r docs-requirements.txt;
      pip install doctr;
    fi

install:
  - pip install -e .

script:
  - pytest --cov
  - flake8 src/ --show-source --statistic --exit-zero
  # test building the docs
  - if [[ $BUILD_DOCS == 'yes' ]]; then make --directory=docs html; fi
  - if [[ $BUILD_INSTALLER == 'yes' ]]; then ./script/makeinstaller.sh; fi

after_success:
  - set -e
  # latest version - push docs for master
  - if [[ $BUILD_DOCS == 'yes' && $TRAVIS_REPO_SLUG == 'livecli/livecli' ]]; then doctr deploy latest; fi
  # stable version - push docs for tags
  - if [[ $BUILD_DOCS == 'yes' && $TRAVIS_REPO_SLUG == 'livecli/livecli' && -n "$TRAVIS_TAG" ]]; then doctr deploy .; fi
  - codecov

addons:
  apt:
    packages:
    - nsis

deploy:
  - provider: releases
    api_key: "${RELEASES_API_KEY}"
    file: "${LIVECLI_INSTALLER_DIST_DIR}/livecli-${TRAVIS_TAG}.exe"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER = yes
      repo: livecli/livecli
  - provider: script
    script: python script/github_releases.py
    skip_cleanup: true
    on:
      tags: true
      condition: $BUILD_INSTALLER == yes
      repo: livecli/livecli
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION == 3.5
      repo: livecli/livecli

doctr:
  build-tags: True
  deploy-repo: livecli/livecli.github.io
  key-path: deploy_key.enc
  require-master: True
